version: '3.7'

services:

  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_VER: v3
    # user: root
    image: nodejs-app:$IMAGE_TAG
    container_name: nodejs-app
    env_file:
      - db.env
    environment:
      DB_HOST: $DB_HOST
    volumes:
      - app-data:/app/data
    networks:
      - test
    ports:
      - 8080:8080

networks:
  test:

volumes:
  app-data:

## This docker-compose.yaml file is the equivalent of following commands

## create docker network
#docker network create test

## build docker image
#docker image build --build-arg API_VER=v3 -t nodejs-app:yellow .

## run image as container
#docker container run -u root -p 8080:8080 -d -e DB_HOST=new-value --env-file=db.env -v app-data:/app/data --network test --name nodejs-app nodejs-app:yellow