apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: nodejs-app:green
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080