apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: nodejs-app:blue
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        command: ["/bin/ash"]
        args: ["-c", "while true; do echo Hello Kubernetes demo; sleep 5;done"]