apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: andreistefanciprian/nodejs-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
        command: ["/bin/ash"]
        args: ["-c", "while true; do echo -en '\n'; printenv DEMO_GREETING DEMO_FAREWELL; sleep 5; done"]