apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: nodejs-app
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-https
spec:
  type: NodePort
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30443
  selector:
    app: proxy