apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0    
      containers:
      - name: nodejs-app
        image: nodejs-app:blue
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/data
          name: data-volume
      volumes:
      - name: data-volume
        hostPath:
          # directory location on host
          path: /data