apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: andreistefanciprian/nodejs-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080