apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nodejs-app
  name: nodejs-app
spec:
  containers:
  - image: andreistefanciprian/nodejs-app
    imagePullPolicy: IfNotPresent
    name: nodejs-app
    ports:
    - containerPort: 8080
