apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nodejs-app
  name: nodejs-app-stray-pod
spec:
  containers:
  - image: nodejs-app:blue
    imagePullPolicy: IfNotPresent
    name: nodejs-app
    ports:
    - containerPort: 8080
