apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app-prod
  name: nodejs-app-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: andreistefanciprian/nodejs-app:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080