apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app-canary
  name: nodejs-app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: nodejs-app
        image: andreistefanciprian/nodejs-app:canary
        imagePullPolicy: Always
        ports:
        - containerPort: 8080