apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomapp
  template:
    metadata:
      labels:
        app: randomapp
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: randomapp
        image: curl:latest
        imagePullPolicy: IfNotPresent
        args:
        - /bin/bash
        - -c
        - sleep 30; touch /tmp/healthy; sleep 600

        startupProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 30
          periodSeconds: 5        
        
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: randomapp
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: randomapp