apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-np
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: nodejs-app
  # enable sessionAffinity if you require to communicate with the same pod
  # sessionAffinity: ClientIP